FROM ghcr.io/richardtin/docker-android-sdk:base

RUN sdkmanager \
    "build-tools;31.0.0"
RUN sdkmanager \
    "build-tools;30.0.3" \
    "build-tools;30.0.2" \
    "build-tools;30.0.1" \
    "build-tools;30.0.0"
RUN sdkmanager \
    "build-tools;29.0.3" \
    "build-tools;29.0.2" \
    "build-tools;29.0.1" \
    "build-tools;29.0.0"
RUN sdkmanager \
    "build-tools;28.0.3" \
    "build-tools;28.0.2" \
    "build-tools;28.0.1" \
    "build-tools;28.0.0"
RUN sdkmanager \
    "build-tools;27.0.3" \
    "build-tools;27.0.2" \
    "build-tools;27.0.1" \
    "build-tools;27.0.0"
RUN sdkmanager \
    "platforms;android-31" \
    "platforms;android-30" \
    "platforms;android-29" \
    "platforms;android-28" \
    "platforms;android-27"
