# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base jdk 11 image
        uses: docker/build-push-action@v2
        with:
          context: base
          file: base/11/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-jdk-11
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-jdk-11
          cache-to: type=inline

      - name: Build and push base jdk 17 image
        uses: docker/build-push-action@v2
        with:
          context: base
          file: base/17/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-jdk-17
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base-jdk-17
          cache-to: type=inline

      - name: Build and push jdk-11-api-34 image
        uses: docker/build-push-action@v2
        with:
          context: api-34
          file: api-34/11/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:jdk-11-api-34
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:jdk-11-api-34
          cache-to: type=inline

      - name: Build and push jdk-17-api-34 image
        uses: docker/build-push-action@v2
        with:
          context: api-34
          file: api-34/17/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:jdk-17-api-34
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:jdk-17-api-34
          cache-to: type=inline

      # - name: Build and push api-34-ndk-r25b image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: api-34-ndk-r25b
      #     file: api-34-ndk-r25b/Dockerfile
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-34-ndk-r25b
      #     cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-34-ndk-r25b
      #     cache-to: type=inline

      # - name: Build and push api-34-ndk-r25c image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: api-34-ndk-r25c
      #     file: api-34-ndk-r25c/Dockerfile
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-34-ndk-r25c
      #     cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:api-34-ndk-r25c
      #     cache-to: type=inline
